name: Super-Linter

on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Run tests
        run: dotnet test
